### ISSUE TITLE
What is identifier-uri

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [genevieve/az-automation#2]
What is the `--identifier-uri` flag used for?  Can I put in any value I want here, or does it have to be a valid URI that points to some actual thing?  What does it get used for?

/cc @genevieve @evanfarrar @nmahoney-pivotal

**Comment by genevieve** [comment]
I think it’s provided to ensure the app has a unique identifier. I don’t believe it has to be a valid uri.

There’s a thread here about what should be provided: https://github.com/Azure/azure-cli/issues/4615#issuecomment-334594735

When the previous version of the azure cli was deprecated, we decided to move the old bash script to a go program that used the new cli. We retained the same inputs and outputs as the previous implementation.

**Comment by Amit-PivotalLabs** [comment]
Got it, thanks!
